name: Populate Exercises

on:
  schedule:
    - cron: '1 18 * * *' # Runs at 12:01 PM CST (Central Standard Time)
    - cron: '0 4 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  populate_exercises:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
            bun-version: 1.0.4

      - name: Install dependencies
        run: bun install
        working-directory: ./scripts

      - name: Run populateJob script
        env:
          SUPABASE_URL: ${{ secrets.PRODUCTION_URL }}
          SUPABASE_KEY: ${{ secrets.PRODUCTION_SERVICE_ROLE_KEY }}
          API_URL: ${{ secrets.BASE_EXERCISE_URL }}
          API_KEY: ${{ secrets.EXERCISE_API_KEY }}
          API_HOST: ${{ secrets.EXERCISE_API_HOST }}
        run: bun populate_exos/index.ts
        working-directory: ./scripts

